### ISSUE TITLE
Add subdivisions of the MB

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/DrosAdultBRAINdomains#7]
As per (https://github.com/VirtualFlyBrain/Management/issues/1#issuecomment-380190246): 
```
So we don't forget: Yoshi gave us the masks for the different mushroom body compartments. It would be good if we can display these in the viewer as well (after they're bridged).
```
Something to do? I can send them to Rob if yes.
```
	Calyx_ped.nrrd
	Lobe_a'b'.nrrd
	Lobe_ab.nrrd
	Lobe_g.nrrd
	
```
MB_compartment_mask.nrrd:
```
	a'1ap.nrrd
	a'1m.nrrd
	a'2ap.nrrd
	a'2m.nrrd
	a'3ap.nrrd
	a'3m.nrrd
	a1c.nrrd
	a1p.nrrd
	a1s.nrrd
	a2c.nrrd
	a2p.nrrd
	a2s.nrrd
	a3c.nrrd
	a3p.nrrd
	a3s.nrrd
	b'1ap.nrrd
	b'1m.nrrd
	b'2a.nrrd
	b'2m.nrrd
	b'2p.nrrd
	b1c.nrrd
	b1p.nrrd
	b1s.nrrd
	b2c.nrrd
	b2p.nrrd
	b2s.nrrd
	g1d.nrrd
	g1main.nrrd
	g2d.nrrd
	g2main.nrrd
	g3d.nrrd
	g3main.nrrd
	g4d.nrrd
	g4main.nrrd
	g5d.nrrd
	g5main.nrrd
	
```

MB_subdomain_layers.nrrd:
```
	a'1_AND_a'b'ap.nrrd
	a'1_AND_a'b'm.nrrd
	a'2_AND_a'b'ap.nrrd
	a'2_AND_a'b'm.nrrd
	a'3_AND_a'b'ap.nrrd
	a'3_AND_a'b'm.nrrd
	a1_AND_abc.nrrd
	a1_AND_abp.nrrd
	a1_AND_abs.nrrd
	a2_AND_abc.nrrd
	a2_AND_abp.nrrd
	a2_AND_abs.nrrd
	a3_AND_abc.nrrd
	a3_AND_abp.nrrd
	a3_AND_abs.nrrd
	b'1_AND_a'b'ap.nrrd
	b'1_AND_a'b'm.nrrd
	b'2a.nrrd
	b'2m.nrrd
	b'2p.nrrd
	b1_AND_abc.nrrd
	b1_AND_abp.nrrd
	b1_AND_abs.nrrd
	b2_AND_abc.nrrd
	b2_AND_abp.nrrd
	b2_AND_abs.nrrd
	g1_AND_g_main.nrrd
	g1_AND_gd.nrrd
	g2_AND_g_main.nrrd
	g2_AND_gd.nrrd
	g3_AND_g_main.nrrd
	g3_AND_gd.nrrd
	g4_AND_g_main.nrrd
	g4_AND_gd.nrrd
	g5_AND_g_main.nrrd
	g5_AND_gd.nrrd
	
```

**Comment by dosumis** [comment]
Need a mapping table to FBbt.  Will give this to Clare to do.

**Comment by mmc46** [comment]
I've uploaded the domains masks @Robbie1977, in JFRC2 space.

The subdomains seems to correspond to only one of the domains (each of them overlaps completely with one of the `MB_compartment_mask.nrrd`), and as we have the `MB_compartment_mask.nrrd` and main compartments I don't think we should use them. Or if we do, we'll need to ask Yoshi about them.

**Comment by dosumis** [comment]
So we should use compartments but not subdomain layers?

**Comment by mmc46** [comment]
Yes, compartments and main compartments.

**Comment by dosumis** [comment]
Had a quick look at mapping MB_compartment nrrds.  Identity not obvious from comparing filenames to synonyms in FBbt.

We have two types of lobe subdivision 

longitudinal = layer/stratum. subtypes, core, inner, outer, surface, posterior 
slice = perpendicular to lobe axis .  These are sometimes referred to as compartments.  Subtypes are numbered in FBbt.  

From the names it looks like MB_compartment_mask.nrrd have names referring to the intersection of slice and layer:

	a1c.nrrd  = alpha lobe slice 1, core layer?
	a1p.nrrd = alpha lobe slice 1, posterior layer?
	a1s.nrrd= alpha lobe slice 1, surface layer?
	
etc. 

Is this correct?  If so, I guess we need to add the intersection terms to FBbt in order to type these.

**Comment by mmc46** [comment]
Yes, that’s correct.

**Comment by Robbie1977** [comment]
@mmc46 @dosumis A question that is probably applicable here and definitely with the VNS is when a new painting of a region appears do we a) update the original b) Keep both and attribute c) archive the old and make only new available?

I personally prefer B as a sustainable model but was wanted to discuss as will probably come up. A good case for scoring of data again as might help enable better versions by consensus.

**Comment by mmc46** [comment]
Two things:
- do you mean having subregions for a region we display? In this case, the subregions would just the additional domains.
- do you mean a region to replace another? 
	What’s the different between a and c, in your options?

I think we should choose one as default, and as a standard. If the new one is better than the old, I don’t think it makes sense to keep both on the same level of prominence. Though still allowing people to access and view the old one might be helpful.

**Comment by Robbie1977** [comment]
a (which is just wrong) would be keeping the same individual term (id) and simply updating the image. c would be making the old individual obsolete and giving the new id as superseding it. C would prevent the old image being returned under our current handling (as I understand it) which is why I prefer the b option with weighted results. I'm not sure I'd want to take responsibility for which is better without some means of community comeback/transparency.

**Comment by mmc46** [comment]
For c, we can consult with BrainName. 
I think it would be confusing for users to see 2 domains for the same neuropil, and not really understand why they’re different, or which to use. 
We’ve adopted, and are displaying the current standard, and so should adapt this standard to new, and better ways, to define the neuropils, and subdomains.

**Comment by dosumis** [comment]
Issue moved to [VirtualFlyBrain/Management #138](https://github.com/VirtualFlyBrain/Management/issues/138) via [**ZenHub**](https://www.zenhub.com/)
